# Generated by Django 5.2.5 on 2026-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodscanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0, help_text='in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list, help_text='List of preparation steps'),
        ),
    ]
